name: Run Coverage

on:
  pull_request:
    branches: [main] # or any branches you want to target
  push:
    branches: [main]

jobs:
  run_tests:
    name: Python (Pull Request Tests)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: "3.12"

      - uses: pyvista/setup-headless-display-action@v3
        with:
          qt: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest --cov --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
