name: Release with uv and semantic-release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv and set Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: "3.12"

      - uses: pyvista/setup-headless-display-action@v3
        with:
          qt: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run semantic-release version

      - name: Publish to Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run semantic-release publish

      - name: Publish to Pypi
        run: uv publish
